import ProviderWrapper from '@/provider';
import { Inter } from 'next/font/google';
import ChatProvider from './ChatProvider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <main
          className='dark:bg-[#21272f] bg-neutral-100'
          data-theme='light dark:dark'
        >
          <ProviderWrapper>
            <ChatProvider>{children}</ChatProvider>
          </ProviderWrapper>
        </main>
      </body>
    </html>
  );
}
