import ProviderWrapper from '@/provider';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <main className='' data-theme='light dark:dark'>
          <ProviderWrapper>
            {children}
            </ProviderWrapper>
        </main>
      </body>
    </html>
  );
}
